apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-client
  labels:
    app.kubernetes.io/name: java-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-client
  template:
    metadata:
      labels:
        app: java-client
        app.kubernetes.io/name: java-client
    spec:
      containers:
      - name: java-client
        image: aakansha321/java-client:latest
        command: ["java", "JavaClient"]
        env:
        - name: API_URL
          value: "http://node-server:3000/api/data"
        resources:
          limits:
            memory: "300Mi"
            cpu: "300m"
