apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-client
  annotations:
    app.kubernetes.io/name: java-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-client
  template:
    metadata:
      labels:
        app: java-client
      annotations:
        app.kubernetes.io/name: java-client
    spec:
      containers:
      - name: java-client
        image: aakansha321/java-client:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            while true; do
              java JavaClient;
              echo "Sleeping for 10 seconds...";
              sleep 10;
            done
        env:
        - name: API_URL
          value: "http://node-server:3000/api/data"
        - name:  OTEL_SERVICE_NAME
          value: java-client
        resources:
          limits:
            memory: "300Mi"
            cpu: "300m"
